Feature/saleor 3384 apollo setup
mirumee/saleor-sdk pull request #100
Opened 2021-05-28 14:20 UTC by MarekChoinski

Usage:

```js
const client = new ApolloClient({
  uri: "https://demo.saleor.io/graphql/",
  cache: new InMemoryCache()
});

ReactDOM.render(
  <SaleorProvider client={client}>
    <App />
  </SaleorProvider>,
  document.getElementById('root')
);
```

2021-05-28 14:20 UTC, patrys commented
Task linked: [SALEOR-3384 Install and setup Apollo Client](https://app.clickup.com/t/2549495/SALEOR-3384)

2021-05-28 14:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mirumee/saleor-sdk?pullRequest=100) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mirumee/saleor-sdk?pullRequest=100) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: karolinakuzniewicz<br/>:x: MarekChoinski<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mirumee/saleor-sdk?pullRequest=100) it.</sub>

2021-05-28 15:50 UTC, jwm0 requested changes

2021-05-28 15:50 UTC, jwm0 commented on package.json
> +    "react": ">=16",
```suggestion
    "react": "^16.8.0 || ^17.0.0",
```
hooks were introduced in 16.8

2021-05-28 15:50 UTC, jwm0 commented on src/react/components/SaleorProvider.tsx
> +        <ApolloProvider client={client}>{children}</ApolloProvider>
ApolloProvider is not needed, we should explicitly pass the apollo client to SaleorContext and extract it inside hooks:
```
function useAuthState(opts) {
  const { apolloClient } = useSaleorContext();

  return useQuery(query, { ...opts, client: apolloClient })
}
```

2021-05-31 10:01 UTC, jwm0 approved these changes

2021-05-31 10:25 UTC, karolinakuzniewicz approved these changes

2021-05-31 10:28 UTC, merged