Type auth methods
mirumee/saleor-sdk pull request #112
Opened 2021-07-08 10:32 UTC by MarekChoinski

2021-07-08 10:32 UTC, patrys commented
Task linked: [SALEOR-3813 Type auth methods](https://app.clickup.com/t/2549495/SALEOR-3813)

2021-07-08 10:54 UTC, krzysztofwolski requested changes

2021-07-08 10:54 UTC, krzysztofwolski commented on src/core/auth.ts
> +  login: (opts: loginOpts) => Promise<FetchResult<Mutation>>;
Its generic type, without response fields introspection

2021-07-08 10:54 UTC, jwm0 requested changes

2021-07-08 10:54 UTC, jwm0 commented on src/core/auth.ts
> +  login: (opts: loginOpts) => Promise<FetchResult<Mutation>>;
The promise return is too generic, we need to type it more strictly. Codegen should generate exact response types for each promise result

2021-07-08 12:50 UTC, krzysztofwolski approved these changes

2021-07-09 09:25 UTC, jwm0 approved these changes

2021-07-09 09:36 UTC, merged