Create global loading state
mirumee/saleor-sdk pull request #127
Opened 2021-08-12 15:07 UTC by MarekChoinski

2021-08-12 22:40 UTC, patrys commented
Task linked: [SALEOR-4184 Global loading state](https://app.clickup.com/t/2549495/SALEOR-4184)

2021-08-19 09:17 UTC, krzysztofwolski approved these changes

2021-08-23 10:07 UTC, jwm0 requested changes

2021-08-30 10:47 UTC, karolinakuzniewicz approved these changes

2021-08-30 11:02 UTC, jwm0 requested changes

2021-08-30 11:02 UTC, jwm0 commented on src/core/auth.ts
> +    refreshToken: false,
I don't think `refreshToken` is necessary, I'd keep it to the initial login methods (login, verifyToken and finnaly oidc logic)

2021-09-06 08:01 UTC, jwm0 approved these changes

2021-09-06 08:01 UTC, merged