Add open id connection methods
mirumee/saleor-sdk pull request #131
Opened 2021-09-07 17:55 UTC by karolinakuzniewicz

2021-09-07 17:55 UTC, patrys commented
Task linked: [SALEOR-3519 Enable login with OpenID Connect](https://app.clickup.com/t/2549495/SALEOR-3519)

2021-09-08 12:17 UTC, jwm0 requested changes

2021-09-09 07:53 UTC, jwm0 requested changes

2021-09-09 07:53 UTC, jwm0 commented on src/core/auth.ts
> +    logout();
It still waits for the response where it should be executed immediately. Move it above `client.mutate` call

2021-09-10 12:18 UTC, jwm0 approved these changes

2021-09-10 12:28 UTC, merged