add channel slug to SaleorState
mirumee/saleor-sdk pull request #56
Opened 2020-11-04 21:46 UTC by AlicjaSzu

2020-11-04 21:46 UTC, patrys commented
Task linked: [SALEOR-614 SDK should keep track of chosen channel](https://app.clickup.com/t/2549495/SALEOR-614)

2020-11-09 14:17 UTC, orzechdev requested changes
I'm not sure, but probably we should allow to change channel more dynamically during app usage. Now, when channel in config changes, the SaleorProvider doesn't reflect its change and queries and mutations will be made with previous channel slug passed as variable.

Anyway, I understand that it might require much more changes to sdk and the most important is to support multichannel feature at all for now. So treat it as a sidenote to our future consideration. After few small changes I think it might be merged.

2020-11-10 11:38 UTC, jwm0 commented on src/api/index.ts
>      this.categories = new CategoriesAPI(client);
We don't, categories are not scoped per sales channel

2020-11-10 11:52 UTC, jwm0 commented
> I'm not sure, but probably we should allow to change channel more dynamically during app usage. Now, when channel in config changes, the SaleorProvider doesn't reflect its change and queries and mutations will be made with previous channel slug passed as variable.

Usually different channels will have different storefront versions (with different env configurations) so this is not a deal breaker right now, but I agree we should look into making this dynamic in future.

2020-11-10 12:56 UTC, orzechdev approved these changes

2020-11-17 10:26 UTC, merged