[SALEOR-3385] Add eslint-plugin-tsdoc
mirumee/saleor-sdk pull request #98
Opened 2021-05-21 11:35 UTC by karolinakuzniewicz

2021-05-21 11:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mirumee/saleor-sdk?pullRequest=98) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mirumee/saleor-sdk?pullRequest=98) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mirumee/saleor-sdk?pullRequest=98) it.</sub>

2021-05-21 12:16 UTC, patrys commented
Task linked: [SALEOR-3385 Read up on TSDoc](https://app.clickup.com/t/2549495/SALEOR-3385)

2021-05-24 08:31 UTC, jwm0 requested changes

2021-05-24 08:31 UTC, jwm0 commented on .eslintrc.js
> +      "version": "999.999.999"
```suggestion
      "version": "detect"
```

2021-05-24 10:08 UTC, merged