Next apollo
mirumee/saleor-sdk pull request #99
Opened 2021-05-25 09:40 UTC by MarekChoinski

Setup Apollo Client. Usage:

```js
   const saleorClient = createSaleorClient({apiUrl: "https://demo.saleor.io/graphql/"});
   const saleor = SaleorSDK(saleorClient);

   useEffect(() => {
     async function fetchMyAPI() {
       const a = await saleor.auth.test();
       console.log(a);
     }
     fetchMyAPI()
   }, [saleor.auth])
```

or

```js
ReactDOM.render(
  <React.StrictMode>
    <SaleorProvider config={{apiUrl: "https://demo.saleor.io/graphql/"}}>
      <App /> 
    </SaleorProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
```

2021-05-25 09:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mirumee/saleor-sdk?pullRequest=99) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mirumee/saleor-sdk?pullRequest=99) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mirumee/saleor-sdk?pullRequest=99) it.</sub>

2021-05-26 09:23 UTC, jwm0 requested changes

2021-05-26 09:23 UTC, jwm0 commented on yarn.lock
>  # yarn lockfile v1
Use `npm`

2021-05-28 14:21 UTC, MarekChoinski commented
Moved #100

2021-05-28 14:21 UTC, closed without merging